In [1]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
X = iris["data"][:, (2,3)]
y = iris["target"]
print("Data: ")
print(X[:5, :])
print("Target: ")
print(y[:5])

Data: 
[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]]
Target: 
[0 0 0 0 0]


In [4]:
# Adding a bias equal to one
X_with_bias = np.c_[np.ones([len(X), 1]), X]
print("Data with bias: ")
print(X_with_bias[:5, :])

Data with bias: 
[[1.  1.4 0.2]
 [1.  1.4 0.2]
 [1.  1.3 0.2]
 [1.  1.5 0.2]
 [1.  1.4 0.2]]


In [5]:
#Set a germ of randomness 
np.random.seed(42)

In [14]:
#Create a validation, train and test set
test_ratio = 0.2
validation_ratio = 0.2
total_size = len(X_with_bias)

test_size = int(total_size * test_ratio)
validation_size = int(total_size * validation_ratio)
train_size = total_size - test_size - validation_size

random_indexes = np.random.permutation(total_size)

X_train = X_with_bias[random_indexes[:train_size]]
y_train = y[random_indexes[:train_size]]
X_validation = X_with_bias[random_indexes[train_size: -validation_size]]
y_validation = y[random_indexes[train_size: -validation_size]]
X_test = X_with_bias[random_indexes[-test_size:]]
y_test = y[random_indexes[-test_size:]]

In [15]:
# Implemenation of one hot encoding
def to_one_hot(y):
    number_of_classes = y.max() + 1
    m = len(y)
    Y_one_hot = np.zeros((m, number_of_classes))
    Y_one_hot[np.arange(m), y] = 1
    return Y_one_hot


2